### ISSUE TITLE
any release plan ?

### ISSUE THREAD

**Issue by dgolja** [bhouse/lita-flowdock#17]
Hello,

any plan to release the new version with the changes applied after May release ?

**Comment by apanzerj** [comment]
@n1tr0g sorry for the delayed response. What May release? Of Flowdock? Of Lita? Of Lita-Flowdock? Sorry. Just let me know what's needed.

ajp

**Comment by dgolja** [comment]
hehe lita-flowdock on rubygems :)

**Comment by apanzerj** [comment]
Working on it. I don't have access to do the release.

**Comment by apanzerj** [comment]
Released. Thanks for your patience.
